version: "3.0"
services:

   web:
     container_name: web
     image: python:3.7
     command: bash -c "cd /src && pip install -r ./requirements.txt && pip install gunicorn && gunicorn --bind 0.0.0.0:5000 main:app --reload"
     ports:
       - "80:5000"
     restart: always
     networks:
       - dev_net
     links:
       - influxdb
       - db
     volumes:
       - ./web:/src
     depends_on:
       - db
       - influxdb

   influxdb:
     container_name: influxdb
     image: influxdb:1.8
     environment:
       - INFLUXDB_HTTP_AUTH_ENABLED=true
       - INFLUXDB_ADMIN_USER=admin #influx admin username
       - INFLUXDB_ADMIN_PASSWORD=securepassword  #influx admin password
       - INFLUXDB_USER=telegraf #influx username
       - INFLUXDB_USER_PASSWORD=secretpassword #influx password
       - INFLUXDB_DB=electric_data
     ports:
       - "8086:8086"
     networks:
       - dev_net
     volumes:
       - ./db/influxdb/data:/var/lib/influxdb
     restart: always

   telegraf:
     container_name: telegraf
     image: telegraf:1.14
     networks:
       - dev_net
     links:
       - influxdb
     volumes:
       - ./db/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
     restart: always
     depends_on:
       - influxdb

   db:
     container_name: db
     image: mysql:8
     environment:
       - MYSQL_RANDOM_ROOT_PASSWORD=yes #random root password
       - MYSQL_USER=myuser #MySQL username
       - MYSQL_PASSWORD=verysecure #MySQL password
       - MYSQL_DATABASE=electric_mon
     networks:
       - dev_net
     restart: always
     volumes:
       - ./db/mysql/initdb/:/docker-entrypoint-initdb.d


   phpmyadmin:
     container_name: phpmyadmin
     image: phpmyadmin/phpmyadmin
     environment:
       - PMA_HOST=db
     ports:
       - "81:80"
     networks:
       - dev_net
     restart: always
     links:
       - db

networks:
   dev_net:
     driver: bridge